# docker-compose up -d
version: '3.1'

services:

  web:
    image: readapp:v1
    restart: always
    ports:
        - 5000:5000
    volumes:
        - /data/readApp:/data/readApp
 
    command:
        - cd data
        - mkdir readApp && cd readApp
        - python man.py
  
